### ISSUE TITLE
"ERROR: Incorrect URL or URL is unreachable. Please, try again later"

### ISSUE THREAD

**Issue by Korb** [appsagg/AppAgg#10]
https://store.steampowered.com/app/1272940/
https://store.steampowered.com/app/1166871/
https://store.steampowered.com/app/1166870/

**Comment by zhdanau** [comment]
Fixed. Thanks!

**Comment by Korb** [comment]
https://store.steampowered.com/app/1974220/

**Comment by zhdanau** [comment]
Fixed

**Comment by Korb** [comment]
https://store.steampowered.com/app/1660080/

**Comment by zhdanau** [comment]
Fixed. Thanks!
