### ISSUE TITLE
YouTube symbol as an icon for all games

### ISSUE THREAD

**Issue by Korb** [appsagg/AppAgg#12]
I don't understand, is it a mistake or an intentional idea to use the YouTube icon to mark games on AppAgg?

![2024-09-14_07-26-23](https://github.com/user-attachments/assets/43c971a2-0811-4d6b-8589-caa111f6ccb8)

Now the sequence of elements in each block is as follows:

1. square cover,
2. YouTube symbol,
3. game title (strangely, it is not the first of all the values),
4. digital distribution platform logo (it would be logical to see it as the second value, after the title, as a clarifying suffix),
5. main game genre,
6. game developer,
7. current price,
8. time since the last price update,
9. lists in which the game is included by the current user
10. rankings (by all users of the platform? AppAgg? SteamDB? Moby Score? mobygames.com?)
11. reviews (by all users - also unclear, where does the statistics come from?)
12. points (whatever that means)
13. operating systems for which game distributions are available on this platform
14. first few words of the game description.

Thus, we can state that there is currently no grouping of values ​​at least by the criteria of “data on the game itself”, “data on the digital distribution platform”, “AppAgg data”.

I propose to structure the information in the game cards, arranging them according to a more obvious logic. And start by moving the icon for **the presence of trailers / gameplay videos** from the beginning of the summary to the part where the data on the game itself (genre, developer, ) or data on AppAgg (lists and points) is grouped.

**Comment by zhdanau** [comment]
Hi Korb!
Thanks for the suggestions. However, if you browse the Android Games directory on your mobile device, and I remove the video icon, you won’t be able to see if a video exists for a game without opening the details page. This isn’t ideal.

**Comment by Korb** [comment]
Maybe change the order of data only for the desktop version of the site?

**Comment by zhdanau** [comment]
What do you think of this version? Please check it.

**Comment by Korb** [comment]
Are you talking about moving the YouTube icon from the beginning of the first line to the beginning of the second line?
![AppAgg Search](https://github.com/user-attachments/assets/61658c19-bde7-4351-ad85-5066df4d1441)
This option seems to me better than the original. However, if we rethink the logic of the data as a whole, I think that its place is in the fourth or fifth lines, that is, in the AppAgg' details of the game (of the third degree of importance).

**Comment by zhdanau** [comment]
Ok, what about this version?

**Comment by Korb** [comment]
I'm not a designer, but the little sticker in the top right corner of the game's square cover seems like the best of the three options to me. Shall we stop there?
