### ISSUE TITLE
Sort by discount amount

### ISSUE THREAD

**Issue by Korb** [appsagg/AppAgg#14]
Currently, the user can sort by the following parameters:

1. Updated
2. Date Added (List)
3. Release Date
4. Points
5. Points (AppAgg)
6. Lists
7. Title Developer
8. Price
9. Rating

I suggest adding sorting by discount size. That is, with such sorting, the list will start with the maximum discounts (value expressed as a percentage) and end with games without discounts.

![2024-12-03_15-47-45](https://github.com/user-attachments/assets/15fe5991-577d-462d-ba17-76f4c89cf3a5)

**Comment by upagg** [comment]
Thanks for the suggestion. It's done.
